# create a docker image with mysql and a default password of admin
version: '3'

name: stockhouse

services:
  db:
    image: bitnami/mysql:latest
    container_name: stockhouse-db
    restart: always
    environment:
      MYSQL_ROOT_USER: dev
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: stockhouse
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    # create a volume for the docker container_name
    volumes:
      - stockhouse-data:/bitnami/mysql/data
    ports:
      - 3306:3306
volumes:
  stockhouse-data:
    driver: local
